import { Card } from '@/components/ui/Card';
import { Zap, Heart, Star, Sparkles } from 'lucide-react';

interface PublicStats {
  totalUrls: number;
  totalClicks: number;
  totalUsers: number;
  uniqueCountries: number;
  uptime: number;
}

interface StatsProps {
  stats?: PublicStats;
}

function formatNumber(num: number): string {
  if (num >= 1000000000) {
    return (num / 1000000000).toFixed(1).replace(/\.0$/, '') + 'B+';
  }
  if (num >= 1000000) {
    return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M+';
  }
  if (num >= 1000) {
    return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K+';
  }
  return num.toString();
}

export function Stats({ stats }: StatsProps) {
  const statsData = [
    {
      value: stats ? formatNumber(stats.totalUrls) : '10M+',
      label: 'Links Created',
      description: 'Short links generated by users worldwide',
      icon: Zap,
      color: 'text-blue-400',
    },
    {
      value: stats ? `${stats.uptime}%` : '99.9%',
      label: 'Uptime',
      description: 'Reliable service you can count on',
      icon: Star,
      color: 'text-yellow-400',
    },
    {
      value: stats ? `${stats.uniqueCountries}+` : '150+',
      label: 'Countries',
      description: 'Users from around the world',
      icon: Sparkles,
      color: 'text-purple-400',
    },
    {
      value: stats ? formatNumber(stats.totalClicks) : '1B+',
      label: 'Clicks Tracked',
      description: 'Total clicks across all short links',
      icon: Heart,
      color: 'text-red-400',
    },
  ];
  return (
    <section className="relative overflow-hidden bg-gradient-to-r from-blue-600 to-purple-600 py-20 text-white">
      {/* Background elements */}
      <div className="absolute inset-0">
        <div className="absolute left-10 top-10 animate-bounce">
          <Sparkles className="h-8 w-8 text-white/20" />
        </div>
        <div className="absolute right-20 top-20 animate-pulse">
          <Heart className="h-6 w-6 text-white/30" />
        </div>
        <div className="absolute bottom-20 left-20 animate-bounce delay-300">
          <Star className="h-5 w-5 text-white/25" />
        </div>
      </div>

      <div className="container relative mx-auto px-4">
        <div className="mx-auto mb-16 max-w-3xl text-center">
          <div className="mb-4 flex items-center justify-center space-x-2">
            <Star className="h-6 w-6 animate-pulse text-yellow-300" />
            <h2 className="text-3xl font-bold sm:text-4xl">
              Trusted by users worldwide
            </h2>
            <Sparkles className="h-6 w-6 animate-bounce text-blue-300" />
          </div>
          <p className="text-lg opacity-90">
            Join thousands of users who trust DV4 Links for their short link
            needs
          </p>
        </div>

        <div className="grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4">
          {statsData.map((stat, index) => (
            <Card
              key={index}
              className="border-white/20 bg-white/10 p-6 text-center text-white backdrop-blur-sm transition-all duration-300 hover:-translate-y-2 hover:scale-105 hover:bg-white/20"
            >
              <div className="mb-3 flex items-center justify-center">
                <stat.icon className={`h-8 w-8 ${stat.color}`} />
              </div>
              <div className="mb-2 text-4xl font-bold">{stat.value}</div>
              <div className="mb-1 text-xl font-semibold">{stat.label}</div>
              <p className="text-sm opacity-80">{stat.description}</p>
            </Card>
          ))}
        </div>
      </div>
    </section>
  );
}
